services:
  postgres_db:
    container_name: postgres_db
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: challenge
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d challenge"]
      interval: 2s
      timeout: 2s
      retries: 10

  go-app:
    container_name: go-app
    build: .
    environment:
      DATABASE_URL: "host=postgres_db user=admin password=admin dbname=challenge sslmode=disable"
      JWT_SECRET: "supersecretjwtkey123456"
    ports:
      - "8080:8080"
    depends_on:
      postgres_db:
        condition: service_healthy

  adminer:
    image: adminer
    container_name: adminer_ui
    restart: always
    ports:
      - "8000:8080"

volumes:
  pgdata:
